sudo: enabled
dist: trusty

services:
 - docker

before_install:
  - sudo add-apt-repository -y ppa:qpid/released
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential make openjdk-8-jdk maven nodejs python-numpy python xz-utils libqpidmessaging2-dev libqpidtypes1-dev libqpidcommon2-dev libqpid-proton8-dev python-qpid python-qpid-messaging python-qpid-proton

script:
 - make big-test
